kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: kubernetes.io/azure-disk
parameters:
  type: Managed
---
apiVersion: apps/v1 ## Kubernetes API Version
kind: Deployment ## Type of resource
metadata:
  labels:
    app: neo4j-db ## Labels given by user
  name: neo4j-db ## Name given to the <kind> resource
  namespace: test ## Namespace in which to deploy the resource
spec:
  replicas: 1
  selector:
    matchLabels: ## Should be same as spec.template.labels
      app: neo4j-db
  template:
    metadata:
      labels: ## Should be same as spec.selector.matchLabels
        app: neo4j-db 
    spec:
      initContainers:
        - name: init-plugins
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: neo4j-plugins
            mountPath: /plugins
          command:
            - "/bin/sh"
            - "-c"
            - |
              curl -L https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.0/apoc-4.2.0.0-core.jar -O
              cp -R apoc-4.2.0.0-core.jar /plugins
      containers:
      - image: neo4j:4.2.1 ## Image Name
        name: neo4j ## Name of container
        env: ## Env variables to pass
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: "algo.*"
          - name: NEO4J_dbms_directories_plugins
            value: "plugins"
        ports: ## Ports to map
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
        volumeMounts: ## Volumes to mount
            - name: neo4j-plugins
              mountPath: "/var/lib/neo4j/plugins"
            - name: neo4j-data
              mountPath: "/var/lib/neo4j/data"
      volumes:
          - name: neo4j-data
            persistentVolumeClaim:
              claimName: neo4j-data-claim
          - name: neo4j-plugins
            persistentVolumeClaim:
              claimName: neo4j-plugin-claim
---
kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: neo4j-data-storage
  labels:
    type: local
    app: neo4j
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: pd-ssd-disk-1
---
kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: neo4j-plugin-storage
  labels:
    type: local
    app: neo4j
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: pd-ssd-disk-1
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: neo4j-data-claim
  namespace: test
  labels:
    app: neo4j-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
  kind: "PersistentVolumeClaim"
  apiVersion: "v1"
  metadata:
    name: neo4j-plugin-claim
    namespace: test
    labels:
      app: neo4j-db
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100M
---
apiVersion: v1
kind: Service
metadata:
    name: neo4j-lb
    namespace: test
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 7474
        targetPort: 7474
        name: http
      - protocol: TCP
        port: 7473
        targetPort: 7473
        name: https
      - protocol: TCP
        port: 7687
        targetPort: 7687
        name: bolt
    selector:
      app: neo4j-db